version: '3.8'

services: 
  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER:  ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    
  backend:
    build: ./backend
    container_name: backend
    restart: always
    ports:
      - "8000:80"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_NAME: appdb
      DB_USER: user
      DB_PASSWORD: password
  
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - backend
    
volumes:
  mysql_data: